import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Link from "next/link";

export const metadata: Metadata = {
  title: {
    template: "%s - Create Next App",
    default: "Create Next App"
  },
  description: "Generated by create next app",
  alternates: {
    types: {
      "application/rss+xml": "https://example.tld/feed.xml"
    },
  }
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
      <nav>
        <ul>
          <li>
            <Link href="/">Root</Link>
          </li>
          <li>
            <Link href="/sub-page-1">Page without any alternate</Link>
          </li>
          <li>
            <Link href="/sub-page-2">Page with alternate defined</Link>
          </li>
        </ul>
      </nav>
        {children}
      </body>
    </html>
  );
}
